name: Auto deploy

on:
  push:
    branches: [ "main", "develop", "compiler" ]

jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents:  write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto deploy to main branch
        if  : github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "/xs508212.xsrv.jp/public_html/main/"

      - name: Auto deploy to develop branch
        if  : github.ref == 'refs/heads/develop'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "/xs508212.xsrv.jp/public_html/develop/"

      - name: Create feature branch
        if:  github.ref == 'refs/heads/compiler/*'
        run: |
          git checkout compiler
          git pull origin compiler
          git subtree push --prefix dist origin compiler:feature/${github.ref#compiler/}
